services:
  caddy:
    container_name: kirby-caddy
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
      - waf_logs:/var/log/waf
    depends_on:
      backend:
        condition: service_healthy      
    networks:
      - app-network
      - infrastructure 
    logging:
      driver: splunk
      options:
        splunk-url: "https://splunk-internal.kirbychope.xyz:8088"
        splunk-token: "${SPLUNK_HEC_TOKEN}"
        splunk-format: json
        splunk-source: "kirby-chope-backend"
        splunk-sourcetype: "docker:container"
        splunk-index: "kirby_chope"
  backend:
    container_name: kirby-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network
      - infrastructure
    extra_hosts:
      - splunk-internal.kirbychope.xyz:127.0.0.1  
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules            # Preserve node_modules in container
      - ./ssl/splunk.crt:/etc/docker/certs.d/splunk-internal.kirbychope.xyz/ca.crt:ro
    logging:
      driver: splunk
      options:
        splunk-url: "https://splunk-internal.kirbychope.xyz:8088" 
        splunk-token: "${SPLUNK_HEC_TOKEN}"
        splunk-format: json
        splunk-source: "kirby-chope-backend"
        splunk-sourcetype: "docker:container"
        splunk-index: "kirby_chope"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  caddy_data:
    name: kirby_caddy_data
    driver: local
  caddy_config:
    name: kirby_caddy_config
    driver: local
  caddy_logs:
    name: kirby_caddy_logs
    driver: local
  waf_logs:
    name: kirby_waf_logs
    driver: local
  backend_logs:
    name: kirby_backend_logs
    driver: local

networks:
  app-network:
    driver: bridge
  infrastructure:
    external: true
    name: kirby_infrastructure 
