services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/caddy:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - splunk
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - "3000"
    logging:
      driver: splunk
      options:
        splunk-url:   "http://127.0.0.1:8088"   # force IPv4 loopback
        splunk-token: "${SPLUNK_HEC_TOKEN}"
        splunk-format: json
    networks:
      - app-network

  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000"   # Splunk Web
      - "8088:8088"   # HEC endpoint
    volumes:
      - splunk_data:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc
    environment:
      SPLUNK_START_ARGS:   --accept-license
      SPLUNK_PASSWORD:     "${SPLUNK_ADMIN_PASSWORD}"
      SPLUNK_ENABLE_HEC:   "true"                    # turn on HTTP Event Collector
      SPLUNK_HEC_TOKEN:    "${SPLUNK_HEC_TOKEN}"
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:
  splunk_data:
  splunk_etc:

networks:
  app-network:
    driver: bridge
