services:
  splunk:
    image: splunk/splunk:latest
    container_name: kirby-splunk  # Fixed container name
    expose:
      - "8000"  # Splunk Web UI
      - "8088"  # HTTP Event Collector (HEC)
    volumes:
      - splunk_data:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: "${SPLUNK_ADMIN_PASSWORD}"
      SPLUNK_ENABLE_HEC: "true"
      SPLUNK_HEC_TOKEN: "${SPLUNK_HEC_TOKEN}"
      SPLUNK_HEC_PORT: 8088
      SPLUNK_HEC_SSL: "false"
    networks:
      - infrastructure
    restart: unless-stopped  # Keep running across reboots
volumes:
  splunk_data:
    name: kirby_splunk_data  # Named volume persists across deployments
  splunk_etc:
    name: kirby_splunk_etc

networks:
  infrastructure:
    name: kirby_infrastructure  # External network name
    driver: bridge