services:
  splunk:
    image: splunk/splunk:latest
    container_name: kirby-splunk  # Fixed container name
    ports:
      - "8000:8000"   # Direct access for debugging
      - "8088:8088"   # HEC endpoint
    volumes:
      - splunk_data:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: "${SPLUNK_ADMIN_PASSWORD:-password123}"
      SPLUNK_ENABLE_HEC: "true"
      SPLUNK_HEC_TOKEN: "${SPLUNK_HEC_TOKEN:-0f9d58fe-a0c1-4256-a670-1295e0e3d9ef}"
      SPLUNK_HEC_PORT: 8088
      SPLUNK_HEC_SSL: "false"
    networks:
      - infrastructure
    restart: unless-stopped  # Keep running across reboots
volumes:
  splunk_data:
    name: kirby_splunk_data  # Named volume persists across deployments
  splunk_etc:
    name: kirby_splunk_etc

networks:
  infrastructure:
    name: kirby_infrastructure  # External network name
    driver: bridge