services:
  splunk:
    image: splunk/splunk:latest
    container_name: kirby-splunk
    expose:
      - "8000"  # Internal only - for Caddy proxy
      - "8088"  # Internal only - for HEC logging
    ports:
      - "8088:8088"
    volumes:
      - splunk_data:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc
      - ./ssl/server.pem:/opt/splunk/etc/auth/server.pem:ro

    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: "${SPLUNK_ADMIN_PASSWORD}"
      SPLUNK_ENABLE_HEC: "true"
      SPLUNK_HEC_TOKEN: "${SPLUNK_HEC_TOKEN}"
      SPLUNK_HTTP_ENABLESSL: true
      SPLUNK_HEC_SSL: true
      SPLUNK_HEC_PORT: 8088
      

    env_file:
      - .idea/.env
    networks:
      - infrastructure
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8000/en-US/account/login"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

volumes:
  splunk_data:
    name: kirby_splunk_data
  splunk_etc:
    name: kirby_splunk_etc

networks:
  infrastructure:
    name: kirby_infrastructure
    driver: bridge
