name: SNYK Scans
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Application Security Testing (Snyk Code)
    runs-on: ubuntu-latest
    needs: sca                        # optional: run after SCA
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk Code Test
        uses: snyk/actions/node@master
        continue-on-error: true        # so that SARIF upload always runs
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif

      - name: Upload SAST results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
